# Generated by Django 4.2.20 on 2025-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("曲名", models.CharField(max_length=100)),
                ("作曲者", models.CharField(max_length=100)),
                ("編曲者", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ('課題曲', '課題曲'),
                            ('クラシック','クラシック'),
                            ('ポップス','ポップス'),
                            ('アンサンブル','アンサンブル'),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
