# Generated by Django 4.2.20 on 2025-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scheduled_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="score",
            name="作曲者",
        ),
        migrations.RemoveField(
            model_name="score",
            name="曲名",
        ),
        migrations.RemoveField(
            model_name="score",
            name="編曲者",
        ),
        migrations.AddField(
            model_name="score",
            name="arr",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="score",
            name="comp",
            field=models.CharField(default="不明", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="scores/images/"),
        ),
        migrations.AddField(
            model_name="score",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="scores/pdf/"),
        ),
        migrations.AddField(
            model_name="score",
            name="title",
            field=models.CharField(default="不明", max_length=100),
            preserve_default=False,
        ),
    ]
