# Generated by Django 4.2.20 on 2025-10-09 03:26

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0002_post_remove_score_作曲者_remove_score_曲名_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="score",
            name="arr",
            field=models.CharField(blank=True, max_length=100, verbose_name="編曲者"),
        ),
        migrations.AlterField(
            model_name="score",
            name="category",
            field=models.CharField(
                choices=[
                    ("課題曲", "課題曲"),
                    ("クラシック", "クラシック"),
                    ("ポップス", "ポップス"),
                    ("アンサンブル", "アンサンブル"),
                    ("その他", "その他"),
                ],
                max_length=100,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="comp",
            field=models.CharField(max_length=100, verbose_name="作曲者"),
        ),
        migrations.AlterField(
            model_name="score",
            name="image_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="pdf_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="pdf"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="title",
            field=models.CharField(max_length=100, verbose_name="曲名"),
        ),
    ]
