# Generated by Django 4.2.20 on 2025-10-13 03:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0003_score_created_at_alter_score_arr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="category",
            field=models.CharField(
                choices=[
                    ("課題曲", "課題曲"),
                    ("クラシック", "クラシック"),
                    ("ポップス", "ポップス"),
                    ("アンサンブル", "アンサンブル"),
                ],
                max_length=100,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.CreateModel(
            name="ScoreFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="file"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="score.score",
                    ),
                ),
            ],
        ),
    ]
