# Generated by Django 4.2.20 on 2025-10-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0004_alter_score_category_scorefile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="score",
            name="image_file",
        ),
        migrations.RemoveField(
            model_name="score",
            name="pdf_file",
        ),
        migrations.AlterField(
            model_name="score",
            name="category",
            field=models.CharField(
                choices=[
                    ("課題曲", "課題曲"),
                    ("クラシック", "クラシック"),
                    ("ポップス", "ポップス"),
                    ("アンサンブル", "アンサンブル"),
                ],
                max_length=100,
                verbose_name="ジャンル",
            ),
        ),
    ]
