# Generated by Django 4.2.20 on 2025-10-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0005_delete_post_remove_score_image_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scorefile",
            name="file",
        ),
        migrations.AddField(
            model_name="scorefile",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="scorefile",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="scorefile",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="score.score"
            ),
        ),
    ]
